<?php
/**
 * Created by PhpStorm.
 * User: silas
 * Date: 14.11.16
 * Time: 22:13
 */

namespace Ainias\CalDav\NoDb\Property;


use Zend\View\Renderer\RendererInterface;

class ParentProperty extends Property
{
    /** @var string */
    private $href;

    /** @var array */
    private $failedProperties;

    /** @var ParentProperty[] */
    private $subParentProperties;

    public function __construct($href = null, $properties = [])
    {
        parent::__construct($properties);
        $this->setHref($href);
        $this->failedProperties = [];
        $this->subParentProperties = [];
    }

    /**
     * @return mixed
     */
    public function getHref()
    {
        return $this->href;
    }

    /**
     * @param mixed $href
     */
    public function setHref($href)
    {
        $this->href = $href;
    }

    /**
     * @return array
     */
    public function getFailedProperties()
    {
        return $this->failedProperties;
    }

    /**
     * @param array $failedProperties
     */
    public function setFailedProperties($failedProperties)
    {
        $this->failedProperties = $failedProperties;
    }

    public function setFailedProperty($name, $value)
    {
        $this->failedProperties[$name] = $value;
    }

    public function getFailedProperty($name)
    {
        if (isset($this->failedProperties[$name]))
        {
            return $this->failedProperties[$name];
        }
        return null;
    }

    public function __toString()
    {
        $propertyString = parent::__toString(); // TODO: Change the autogenerated stub
        $href = $this->getHref();

        $failedPropertyString = "";
        $properties = $this->getFailedProperties();
        foreach ($properties as $name => $value)
        {
            $failedPropertyString .= $this->singlePropertyToString($name, $value).PHP_EOL;
        }

        if (count($this->getProperties()) > 0)
        {
            $propertyString = <<<XML
        <d:propstat>
            <d:prop>
                $propertyString
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
XML;
        }
        else
        {
            $propertyString = "";
        }

        if (count($this->failedProperties) > 0)
        {
            $failedPropertyString = <<<XML
        <d:propstat>
            <d:prop>
                $failedPropertyString
            </d:prop>
            <d:status>HTTP/1.1 404 Not Found</d:status>
        </d:propstat>
XML;
        }
        else
        {
            $failedPropertyString = "";
        }
        return <<<XML
<d:response>
        <d:href>$href</d:href>
        $propertyString
        $failedPropertyString
    </d:response>
XML;
    }

    protected function doPrepare(RendererInterface $renderer)
    {
        $this->setHref($renderer->url("calDav", ["propertyHref" => $this->getHref()]));
    }

    public function getAsReference()
    {
        return new ReferenceProperty($this->getHref());
    }

    /**
     * @return ParentProperty[]
     */
    public function getSubParentProperties()
    {
        return $this->subParentProperties;
    }

    /**
     * @param ParentProperty[] $subParentProperties
     */
    public function setSubParentProperties($subParentProperties)
    {
        $this->subParentProperties = [];
        foreach ($subParentProperties as $parentProperty)
        {
            $this->addSubParentProperty($parentProperty);
        }
    }

    public function addSubParentProperty(ParentProperty $subParentProperty)
    {
        $this->subParentProperties[$subParentProperty->getHref()] = $subParentProperty;
    }
}