<?php
/**
 * Created by PhpStorm.
 * User: silas
 * Date: 14.11.16
 * Time: 22:13
 */

namespace Ainias\CalDav\NoDb\Property;


class ParentProperty extends Property
{
    /** @var string */
    private $href;

    /** @var array */
    private $failedProperties;

    /**
     * @return mixed
     */
    public function getHref()
    {
        return $this->href;
    }

    /**
     * @param mixed $href
     */
    public function setHref($href)
    {
        $this->href = $href;
    }

    /**
     * @return array
     */
    public function getFailedProperties()
    {
        return $this->failedProperties;
    }

    /**
     * @param array $failedProperties
     */
    public function setFailedProperties($failedProperties)
    {
        $this->failedProperties = $failedProperties;
    }

    public function setFailedProperty($name, $value)
    {
        $this->failedProperties[$name] = $value;
    }

    public function getFailedProperty($name)
    {
        if (isset($this->failedProperties[$name]))
        {
            return $this->failedProperties[$name];
        }
        return null;
    }

    public function __toString()
    {
        $propertyString = parent::__toString(); // TODO: Change the autogenerated stub
        $href = $this->getHref();

        $failedPropertyString = "";
        $properties = $this->getFailedProperties();
        foreach ($properties as $name => $value)
        {
            $failedPropertyString .= $this->singlePropertyToString($name, $value).PHP_EOL;
        }

        if (count($this->getProperties()) > 0)
        {
            $propertyString = <<<XML
        <d:propstat>
            <d:prop>
                $propertyString
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
XML;
        }
        else
        {
            $propertyString = "";
        }

        if (count($this->failedProperties) > 0)
        {
            $failedPropertyString = <<<XML
        <d:propstat>
            <d:prop>
                $failedPropertyString
            </d:prop>
            <d:status>HTTP/1.1 404 Not Found</d:status>
        </d:propstat>
XML;
        }
        else
        {
            $failedPropertyString = "";
        }
        return <<<XML
<d:response>
        <d:href>$href</d:href>
        $propertyString
        $failedPropertyString
    </d:response>
XML;
    }
}