<\?xml version="1.0" encoding="utf-8" ?>
<d:multistatus>
    <d:response>
        <d:href>/caldav/cal.php/calendars/silas/</d:href>
        <d:propstat>
            <d:prop>
                <cs:getctag />
            </d:prop>
            <d:status>HTTP/1.1 404 Not Found</d:status>
        </d:propstat>
    </d:response>
    <d:response>
        <d:href>/caldav/cal.php/calendars/silas/Ju-FeG-Le/</d:href>
        <d:propstat>
            <d:prop>
                <cs:getctag>0</cs:getctag>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
    <d:response>
        <d:href>/caldav/cal.php/calendars/silas/outbox/</d:href>
        <d:propstat>
            <d:prop>
                <cs:getctag />
            </d:prop>
            <d:status>HTTP/1.1 404 Not Found</d:status>
        </d:propstat>
    </d:response>
</d:multistatus>