<?php
echo '<?xml version="1.0" encoding="utf-8" ?>'.PHP_EOL;
?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
    <response>
        <href>/caldav/users/</href>
        <propstat>
            <prop>
                <C:calendar-home-set>
                    <href>/davical/caldav.php/Silas/</href>
                </C:calendar-home-set>
                <C:calendar-user-address-set>
                    <href>mailto:silas42897@t-online.de</href>
                    <href>/davical/caldav.php/Silas/</href>
                </C:calendar-user-address-set>
                <C:schedule-inbox-URL>
                    <href>/davical/caldav.php/Silas/.in/</href>
                </C:schedule-inbox-URL>
                <C:schedule-outbox-URL>
                    <href>/davical/caldav.php/Silas/.out/</href>
                </C:schedule-outbox-URL>
            </prop>
            <status>HTTP/1.1 200 OK</status>
        </propstat>
    </response>
</multistatus>

