<?php
echo '<?xml version="1.0" encoding="utf-8" ?>'.PHP_EOL;
?>
<multistatus xmlns="DAV:">
    <response>
        <href>/caldav/appointment/0d97f0ef-2a54-4502-a257-3ade074df206.ics</href>
        <propstat>
            <prop>
                <getcontenttype>text/calendar; component=vevent</getcontenttype>
                <getetag>"661f503450b61ee5c53a212f5a2569b47"</getetag>
            </prop>
            <status>HTTP/1.1 200 OK</status>
        </propstat>
    </response>
    <sync-token>data:,2</sync-token>
</multistatus>

